title: AI Blog  
author: Cibin Anoop 
description: Exploring AI technologies and their uses  
remote_theme: jekyll-theme-name  
plugins:
  - jekyll-seo-tag
navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
